# Site settings
title: Device Lab
description: Nomad Device Lab is a collection of mobile devices that helps you do better mobile testing.
baseurl: ""
url: "http://devicelab.co.za"

# Build settings
markdown: kramdown

sass:
  style: compressed

css-version: 1.7
